basemap:
  update:
    # 固定期間モード（コメントアウト）
    # type: "fix"
    # data:
    #   start: "2024-01-17T00:00:00+09:00"
    #   end: "2024-01-22T00:00:00+09:00"
    
    # 周期モード
    type: "periodic"
    data:
      lookback: "10D"  # 過去10日間のデータを使用
    
    # スケジュール設定（scheduler用）
    schedule:
      interval: "daily"     # 毎日更新
      time: "02:00"        # 実行時刻（深夜2時）

  heatmap:
    effective_radius: 0.1
    z_axis: 0.5
    resolution: 100

  detabn:
    mw: 5
    rt: 1.0
    th: 0.0
    manual_mask:
      - [20, 20, 30, 30]
      - [50, 50, 55, 55]

  ignore_period:
    - start: "2025-03-01T00:00:00+09:00"
      end: "2025-03-01T01:00:00+09:00"
    - start: "2025-03-02T00:00:00+09:00"
      end: "2025-03-02T00:10:00+09:00"

  area:
    - type: "ellipse"
      x: -0.11337024374999997
      y: -0.29319890625
      radX: 0.32803095468943977
      radY: 0.2082443701118354
      rot: 0
    - type: "ellipse"
      x: -0.39223498125
      y: 0.10164228749999998
      radX: 0.3132879904337346
      radY: 0.33908817788121864
      rot: 0
    - type: "ellipse"
      x: 0.20589078749999998
      y: -0.011727956250000005
      radX: 0.22298733436754056
      radY: 0.2266730754314668
      rot: 0

  addplot:
    interval: "10m"
    lookback_period: "2H"

  source_tags:
    - "POW:7I1032.PV"
    - "POW:7I1033.PV"
    - "POW:7I1021.PV"
    - "POW:7W105A1.CPV"
    - "POW:7W105B1.CPV"
    - "POW:7F151A.PV"
    - "POW:7F151B.PV"
    - "POW:7F151C.PV"
    - "POW:7F151D.PV"
    - "POW:7I1011.PV"
    - "POW:7I1012.PV"
    - "POW:7I1022.PV"
    - "POW:7I1023.PV"
    - "POW:7I102A.PV"
    - "POW:7I102B.PV"
    - "POW:7I1034.PV"
    - "POW:7I1031.PV"
    - "POW:7I104.PV"
    - "POW:7T105A1.PV"
    - "POW:7T105B1.PV"

  gtags:
    - "POW:7I1034.PV.MA5"
    - "POW:7T105B1.PV.MA5"

# PI-Ingester専用設定
pi_integration:
  enabled: true
  # output_filename は自動生成: 7th-untan.csv

# toorPIA連携設定
toorpia_integration:
  enabled: true
  api_url: "http://localhost:3000"
  timeout: 300  # seconds
  
  # API エンドポイント設定
  endpoints:
    fit_transform: "/data/fit_transform"
    addplot: "/data/addplot"
  
  # 認証設定
  auth:
    api_key: "toorpia_1967e5ce981183c06013c09cd59074d0d7e4d6b1ece15d3c"
    auto_refresh: true
  
  # basemap処理設定
  basemap_processing:
    mode: "fit_transform"
    parameters:
      label: "7th-untan"
      description: "7号機脱硫装置 基盤マップ"
      weight_option_str: "1:0"
      type_option_str: "1:date"
      # identnaパラメータ（正常領域識別）
      identna_resolution: 100        # メッシュ解像度
      identna_effective_radius: 0.1  # 有効半径比率
    
    # スケジュール設定
    schedule:
      trigger: "basemap_update"
      data_period: "basemap_lookback"
  
  # addplot処理設定
  addplot_processing:
    mode: "addplot"
    parameters:
      weight_option_str: "1:0"
      type_option_str: "1:date"
      # detabnパラメータ（異常度判定）
      detabn_max_window: 5           # 最大ウィンドウサイズ
      detabn_rate_threshold: 1.0     # 異常率閾値
      detabn_threshold: 0            # 正常領域閾値
      detabn_print_score: true       # 詳細スコア情報出力
    
    # スケジュール設定
    schedule:
      trigger: "addplot_interval"
      data_period: "addplot_lookback"
  
  # ログ設定
  logging:
    level: "INFO"
    filename: "toorpia_analyzer.log"
    max_size_mb: 10
    backup_count: 5
    console: true
    
  # バリデーション設定
  validation:
    timeout_seconds: 300
    required_response_fields: ["message", "resdata"]
    required_resdata_fields: ["mapNo"]
  
  # 状態管理
  state:
    last_map_no: null  # 自動更新
    last_basemap_update: null  # 自動更新
    last_addplot_update: null  # 自動更新
