version: '3.8'

services:
  if-hub:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: if-hub-prod
    ports:
      - "${EXTERNAL_PORT:-3001}:3000"
    volumes:
      - ../src:/app/src
      - ../static_equipment_data:/app/static_equipment_data
      - ../tag_metadata:/app/tag_metadata
      - ../gtags:/app/gtags        # gtag定義とカスタム実装
      - ../logs:/app/logs
      - ../db:/app/db  # データベースファイル用のボリューム
      - ../package.json:/app/package.json
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EXTERNAL_PORT=${EXTERNAL_PORT:-3001}
      - EXTERNAL_API_URL=https://external-system-url/api  # replace this with the external system's URL
    restart: unless-stopped
