version: '3.8'

services:
  if-hub:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: if-hub-prod
    ports:
      - "${EXTERNAL_PORT:-3001}:3000"
    volumes:
      - ../src:/app/src
      - ../static_equipment_data:/app/static_equipment_data
      - ../tag_metadata:/app/tag_metadata
      - ../gtags:/app/gtags        # gtag定義とカスタム実装
      - ../logs:/app/logs
      - ../db:/app/db  # データベースファイル用のボリューム
      - ../package.json:/app/package.json
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EXTERNAL_PORT=${EXTERNAL_PORT:-3001}
      - DB_PATH=/app/db/if_hub.db  # データベースファイルのパス
      - EXTERNAL_API_URL=https://external-system-url/api  # replace this with the external system's URL
      - TZ=${TZ:-Asia/Tokyo}  # ホストから取得したタイムゾーン、未設定の場合は日本時間
    restart: unless-stopped

  pi-ingester:
    build:
      context: ../ingester
      dockerfile: Dockerfile
    container_name: if-hub-pi-ingester-prod
    volumes:
      - ../configs:/app/configs:ro           # 設定ファイル（読み取り専用）
      - ../logs:/app/logs                    # ログファイル
      - ../static_equipment_data:/app/static_equipment_data  # CSV出力先
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - if-hub
    networks:
      - default
